### PR TITLE
check list containing list-items as direct child

### PR DESCRIPTION
**Pull request by nuxodin**
`li` elements may contain various elements:
https://jsfiddle.net/7xhn3w5c/3/

### CODE REVIEW

**Review by AustinGil — APPROVED** [review]

**Comment by AustinGil** [comment]
Thanks @nuxodin. I like it!

I haven't fully implemented the lint-html feature yet. Still not sure how well it fits into the library, but it's a cool idea and I appreciate your contribution :)

**Comment by nuxodin** [comment]
ups, my latest PR removed this PR

**Comment by AustinGil** [comment]
Yep. I read that backwards and see the issue. Fixed now. Thanks for pointing it out.

**Pull request merged**
